version: '3.7'

services:
  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_DATABASE=cga
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - TZ=Africa/Yaounde
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  backend:
    build:
      context: backend
    image: cga-backend
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "cd /usr/src/app && node dabase.js && npm start"
    ports:
      - 8080:8080

  frontend:
    build:
      context: frontend/cga
    image: cga-frontend
    restart: always
    depends_on:
      - mysql
    ports:
      - 3000:3000
